### ISSUE TITLE
如何清除浮动

### ISSUE THREAD

**Issue by monkeyart** [monkeyart/interview#40]
清楚浮动的意义：让父亲包裹浮动子元素，减少对其他元素的影响

**方法:**

- clear: left

    要求该盒的top border边位于源文档中在此之前的元素形成的所有左浮动盒的底边下方

- clear: right

    要求该盒的top border边位于源文档中在此之前的元素形成的所有右浮动盒的底边下方

- clear: both

    要求该盒的top border边位于源文档中在此之前的元素形成的所有左浮动盒和右浮动盒的底边下方

clear 属性举例

- 查看范例 [http://js.jirengu.com/taja/1/edit](http://js.jirengu.com/taja/1/edit)
- 思考：对box2设置clear: right有效吗

注意：移动的对象是自己，不是其他元素

使用如下代码

```css
.clearfix::after {
content: '';
display: block;
clear: both;
}
```

题目来自饥人谷
